version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save cache
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Inject Firebase configuration
          command: |
            echo "export const environment = { production: true, firebase: { apiKey: '${FIREBASE_API_KEY}', authDomain: '${FIREBASE_AUTH_DOMAIN}', databaseURL: '${FIREBASE_DATABASE_URL}', projectId: '${FIREBASE_PROJECT_ID}', storageBucket: '${FIREBASE_STORAGE_BUCKET}', messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}', appId: '${FIREBASE_APP_ID}' } }" > src/environments/environment.prod.ts
      - run:
          name: Build project
          command: npm run build -- --prod
      - deploy:
          name: Deploy to Firebase Hosting
          command: |
            sudo npm install -g firebase-tools
            firebase deploy --only hosting --token $FIREBASE_TOKEN

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
